name: Package macOS version on intel architecture

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up a virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Download ffmpeg
        shell: python
        run: |
          import static_ffmpeg
          static_ffmpeg.add_paths()
      
      - name: Build with PyInstaller
        run: |
          pyinstaller anaouder.spec
          
      - name: Upload built application
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: dist/
